version: '3.3'

services:

  combiner:
    build:
      context: ../
      dockerfile: components/base/Dockerfile
    image: "esn-fedn-combiner:latest"
    environment:
      - PYTHONUNBUFFERED=0
      - GET_HOSTS_FROM=dns
    working_dir: /app/client
    command: sh -c "sleep 5 && fedn run combiner -in ./config/settings-combiner.yaml"
    volumes:
      - /home/ubuntu/fedn/config:/app/client/config
      - /home/ubuntu/fedn/tmp/c1-models:/tmp/models
    ports:
      - 12080:12080

